import Head from 'next/head'
import { useState } from 'react';
import Image from 'next/image'

import { Auth } from '../components/Auth';
import Cookies from 'universal-cookie'
import Login from './Login';

export default function Home(props) {
    
    
  const cookie = new Cookies();
  const [isAuth, setIsAuth] = useState(cookie.get("auth-token"));

      
  return (
  
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
    <Auth/>&&
    <div>hello</div>
    
  
    
      </main>
    </>
  )
}
